### PR TITLE
fix: [internal] Properly set login time for custom auth

### LINKED ISSUE #5797: Update users.last_login with external auth user login
2.4.121

We are now using `CustomAuth` external authenticated user logins into MISP. Works real nicely: thanks!

Would it be possible to have the db `users.last_login` updated? Also, perhaps a login row in the `logs` table?

I do see that the db `logs` table gets a new row for every WebUI click where
```
logs.title = "Successful authentication using MyLogins External authentication key"
```
However, it is difficult to deduce which one is an initial login. I believe a non-auth user login does cause a distinct row insert into `logs`, but not for ext auth.

Open to suggestions on how we may collect external auth user login stats. Thanks...

### PR DESCRIPTION
**Pull request by JakubOnderka**
#### What does it do?

Will fix #5797

#### Questions

- [ ] Does it require a DB change?
- [x] Are you using it in production?
- [ ] Does it require a change in the API (PyMISP for example)?

### CODE REVIEW

File: app/Model/User.php [hunk 1]
```diff
@@ -1324,6 +1324,22 @@ public function registerUser($added_by, $registration, $org_id, $role_id) {
         }
     }
 
+    /**
+     * @param array $user
```
Comment (chrisinmtown) [inline app/Model/User.php:1330]: Please state what the function does (or should do)

File: app/Controller/UsersController.php [hunk 2]
```diff
@@ -1231,13 +1231,7 @@ private function _postlogin()
       ));
       $lastUserLogin = $user['User']['last_login'];
       unset($user['User']['password']);
-      $user['User']['action'] = 'login';
-      $user['User']['last_login'] = $this->Auth->user('current_login');
-      $user['User']['current_login'] = time();
-      $this->User->save($user['User'], true, array('id', 'last_login', 'current_login'));
-      if (empty($this->Auth->authenticate['Form']['passwordHasher']) && !empty($passwordToSave)) {
```
Comment (chrisinmtown) [inline app/Controller/UsersController.php:1238]: what about this special treatment of passwords?  The updateLoginTimes() function does not cover this

File: app/Controller/AppController.php [hunk 3]
```diff
@@ -1101,6 +1101,7 @@ private function __customAuthentication($server)
                 if ($user['User']) {
                     unset($user['User']['gpgkey']);
                     unset($user['User']['certif_public']);
+                    $this->User->updateLoginTimes($user['User']);
```
Comment (chrisinmtown) [inline app/Controller/AppController.php:1104]: I believe, but am not 100% certain, this will update the login times for every page request. Ideally the server should do the update only on a transition from unauthenticated to authenticated.  But detecting that transition in a stateless server is difficult!

File: app/Controller/UsersController.php (hunk 2 above)
Comment (JakubOnderka) [reply app/Controller/UsersController.php:1238]: Yes, because this functionality is broken. It depends on `$passwordToSave` variable, that is not defined in that function.

File: app/Controller/AppController.php (hunk 3 above)
Comment (JakubOnderka) [reply app/Controller/AppController.php:1104]: This should be OK, because after login, user has session stored in cookie. So this login process is repeated just after session expires.

File: app/Model/User.php (hunk 1 above)
Comment (JakubOnderka) [reply app/Model/User.php:1330]: Thanks, done.

File: app/Controller/AppController.php (hunk 3 above)
Comment (chrisinmtown) [reply app/Controller/AppController.php:1104]: Ok so that's how you detect the transition - if there's no MISP cookie, call login which sets the cookie AND updates the current & last login times, do I have that correct?

**Review by chrisinmtown — APPROVED** [review]

**Comment by chrisinmtown** [comment]
If you don't mind a distracting question, please point me to the code/function where the last_login is updated today in the normal non-custom-auth path.  I really struggled to find it.

**Comment by iglocska** [comment]
> If you don't mind a distracting question, please point me to the code/function where the last_login is updated today in the normal non-custom-auth path. I really struggled to find it.

function _postlogin() in the UsersController. It is called on the login function as well as email_otp() function.

Also, this is not the field you want to use for auditing most likely, but rather the audit logs (action == login)

File: app/Controller/UsersController.php (hunk 2 above)
Comment (iglocska) [reply app/Controller/UsersController.php:1238]: Yep, looks like this was broken when the login function was split in two with _postlogin(). We can clean quite a bit of code up, it's from a few years ago when we transitioned to bcrypt for the password hashing.

**Comment by chrisinmtown** [comment]
> function _postlogin() in the UsersController. It is called on the login function as well as email_otp() function.

Thanks for that.  I need to learn more about PHP before I can understand your answer.  I naively tried grep to find invocations of the login() function in UsersController but found none.

File: app/Controller/AppController.php (hunk 3 above)
Comment (JakubOnderka) [reply app/Controller/AppController.php:1104]: Yes, thats correct.

**Comment by iglocska** [comment]
> > function _postlogin() in the UsersController. It is called on the login function as well as email_otp() function.
> 
> Thanks for that. I need to learn more about PHP before I can understand your answer. I naively tried grep to find invocations of the login() function in UsersController but found none.

Basically every public function in a controller is user exposed and invoked by querying the given endpoint: baseurl/[controller_alias]/[controller_function]

However, _postlogin() is a private function and only invoked by other functions in the controller (such as login())

Hope that makes sense!
