### PR TITLE
fix: improve error handling when supervisor is not available or conne…

### LINKED ISSUE #7988: Internal Error when browsing server settings if supervisor is not running
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| MISP version / git hash   | 2.4.151

### Expected behavior
Server settings page should load even if Supervisor is not running.
Reported by @eCrimeLabs via Gitter.

### Actual behavior
Server settings fails to load and gives Internal Error.

### Steps to reproduce the behavior
1. Enable Supervisor background jobs
2. Stop Supervisor service
3. Browse server settings page -> Internal Error

### PR DESCRIPTION
**Pull request by righel**
#### What does it do?

If it fixes an existing issue, please use github syntax: `#<IssueID>`
* Fixes #7988 and provides better error handling when Supervisor is not available.
* Show a warning message in Server Settings -> Workers tab when connection to Supervisor failed, log errors.
image

#### Questions

- [ ] Does it require a DB change?
- [ ] Are you using it in production?
- [ ] Does it require a change in the API (PyMISP for example)?

### CODE REVIEW

File: app/Lib/Tools/BackgroundJobsTool.php [hunk 1]
```diff
@@ -278,9 +278,19 @@ public function clearQueue($queue): bool
...
     public function getWorkers(): array
     {
-        $workers = [];
-        $procs = $this->getSupervisor()->getAllProcesses();
+        try {
+            $procs = $this->getSupervisor()->getAllProcesses();
+        } catch (\Exception $exception) {
+            CakeLog::error(
+                "An error occured when getting the workers statuses via Supervisor API: {$exception->getMessage()}",
+                0,
```
Comment (JakubOnderka) [inline app/Lib/Tools/BackgroundJobsTool.php]: I think for `CakeLog::error`, there are not parameters like code or exception.

```php
public static function error($message, $scope = array())
```
