### PR TITLE
fix: [Validation] Add validation for S3 bucket prefix when deleting e…

### LINKED ISSUE #10243: Bug: Regression in AttachmentTool->deleteAll(). Parameter Must be a string
### Actual behavior

When trying to delete an event (Or accept a delegation, which appareantly deletes an event) while storing attachments in S3 fails due to Input validation in the S3 PHP SDK. The sent value for the 'prefix' (a.k.a Directory, $eventId in our case) must be a string. Note that this fails even if the event does not have any attachments.
The user is met by "An Internal error Has Occured" and the event does not get deleted.

See stack trace below

### Expected behavior

Event and any attachments stored in S3 is deleted. With no errors to the user.

### Steps to reproduce

Install MISP host (We're using https://github.com/NUKIB/misp)
Set up S3 Storage (we're using MinIO but the same bug -should- be present in AWS S3 as well since the validation is done before the request is sent)
Create an event
Try to delete an event

### Version

2.5.7

### Operating System

Redhat (Base image for container: almalinux:9)

### Operating System version

9

### PHP version

8

### Browser

Chrome

### Browser version

Latest

### Relevant log output

```shell
2025-02-24 14:19:19 Error: Delete of event file directory failed.
[Aws\Exception\UnresolvedEndpointException] Input parameter `Prefix` is the wrong type. Must be a String.
Stack Trace:
#0 /var/www/MISP/app/Vendor/aws/aws-sdk-php/src/EndpointV2/Ruleset/Ruleset.php(90): Aws\EndpointV2\Ruleset\RulesetParameter->validateInputParam()
#1 /var/www/MISP/app/Vendor/aws/aws-sdk-php/src/EndpointV2/Ruleset/Ruleset.php(65): Aws\EndpointV2\Ruleset\Ruleset->validateInputParameters()
#2 /var/www/MISP/app/Vendor/aws/aws-sdk-php/src/EndpointV2/EndpointProviderV2.php(52): Aws\EndpointV2\Ruleset\Ruleset->evaluate()
#3 /var/www/MISP/app/Vendor/aws/aws-sdk-php/src/EndpointV2/EndpointV2Middleware.php(105): Aws\EndpointV2\EndpointProviderV2->resolveEndpoint()
#4 /var/www/MISP/app/Vendor/aws/aws-sdk-php/src/Auth/AuthSelectionMiddleware.php(97): Aws\EndpointV2\EndpointV2Middleware->__invoke()
#5 /var/www/MISP/app/Vendor/aws/aws-sdk-php/src/InputValidationMiddleware.php(73): Aws\Auth\AuthSelectionMiddleware->__invoke()
#6 /var/www/MISP/app/Vendor/aws/aws-sdk-php/src/Middleware.php(90): Aws\InputValidationMiddleware->__invoke()
#7 /var/www/MISP/app/Vendor/aws/aws-sdk-php/src/S3/S3Client.php(772): Aws\Middleware::Aws\{closure}()
#8 /var/www/MISP/app/Vendor/aws/aws-sdk-php/src/S3/S3Client.php(795): Aws\S3\S3Client::Aws\S3\{closure}()
#9 /var/www/MISP/app/Vendor/aws/aws-sdk-php/src/S3/S3Client.php(729): Aws\S3\S3Client::Aws\S3\{closure}()
#10 /var/www/MISP/app/Vendor/aws/aws-sdk-php/src/S3/S3Client.php(748): Aws\S3\S3Client::Aws\S3\{closure}()
#11 /var/www/MISP/app/Vendor/aws/aws-sdk-php/src/Middleware.php(58): Aws\S3\S3Client::Aws\S3\{closure}()
#12 /var/www/MISP/app/Vendor/aws/aws-sdk-php/src/S3/SSECMiddleware.php(59): Aws\Middleware::Aws\{closure}()
#13 /var/www/MISP/app/Vendor/aws/aws-sdk-php/src/IdempotencyTokenMiddleware.php(77): Aws\S3\SSECMiddleware->__invoke()
#14 /var/www/MISP/app/Vendor/aws/aws-sdk-php/src/AwsClientTrait.php(64): Aws\IdempotencyTokenMiddleware->__invoke()
#15 /var/www/MISP/app/Vendor/aws/aws-sdk-php/src/AwsClientTrait.php(58): Aws\AwsClient->executeAsync()
#16 /var/www/MISP/app/Vendor/aws/aws-sdk-php/src/AwsClientTrait.php(86): Aws\AwsClient->execute()
#17 /var/www/MISP/app/Lib/Tools/AWSS3Client.php(132): Aws\AwsClient->__call()
#18 /var/www/MISP/app/Lib/Tools/AttachmentTool.php(282): AWSS3Client->deleteDirectory()
#19 /var/www/MISP/app/Model/Event.php(410): AttachmentTool->deleteAll()
#20 /var/www/MISP/app/Lib/Tools/BetterCakeEventManager.php(21): Event->beforeDelete()
#21 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(2695): BetterCakeEventManager->dispatch()
#22 /var/www/MISP/app/Model/EventDelegation.php(45): Model->delete()
#23 /var/www/MISP/app/Controller/EventDelegationsController.php(163): EventDelegation->transferEvent()
#24 [internal function]: EventDelegationsController->acceptDelegation()
#25 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(500): ReflectionMethod->invokeArgs()
#26 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#27 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#28 /var/www/MISP/app/webroot/index.php(107): Dispatcher->dispatch()
#29 {main}
2025-02-24 14:19:19 Error: [InternalErrorException] Delete of event file directory failed. Please report to administrator.
Request URL: /event_delegations/acceptDelegation/5
Stack Trace:
#0 /var/www/MISP/app/Lib/Tools/BetterCakeEventManager.php(21): Event->beforeDelete()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(2695): BetterCakeEventManager->dispatch()
#2 /var/www/MISP/app/Model/EventDelegation.php(45): Model->delete()
#3 /var/www/MISP/app/Controller/EventDelegationsController.php(163): EventDelegation->transferEvent()
#4 [internal function]: EventDelegationsController->acceptDelegation()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(500): ReflectionMethod->invokeArgs()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#8 /var/www/MISP/app/webroot/index.php(107): Dispatcher->dispatch()
#9 {main}
```

### Extra attachments

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by dygland**
…vents

## Generic requirements in order to contribute to MISP:

* One Pull Request per fix/feature/change/...
* Keep the amount of commits per PR as small as possible: if for any reason, you need to fix your commit after the pull request, please squash the changes in one single commit (or tell us why not)
* Always make sure it is mergeable in the default branch (as of today 2020-05-05: branch 2.4)
* Please make sure Travis CI works on this request, or update the test cases if needed
* Any major changes adding a functionality should be disabled by default in the config

#### What does it do?
Resolves #10243
Adds functionality to ensure that the eventId submitted to S3 when using the deleteAll function is a String and therefore validated correctly by the S3 sdk.

#### Questions

- [x] Does it require a DB change? NO
- [x] Are you using it in production? YES
- [x] Does it require a change in the API (PyMISP for example)? NO

### CODE REVIEW

File: app/Lib/Tools/AttachmentTool.php [hunk 1]
```diff
@@ -278,8 +278,25 @@ protected function _delete($shadow, $eventId, $attributeId, $pathSuffix = '')
...
     {
         if ($this->attachmentDirIsS3()) {
+            // AWS S3 SDK validates that the Directory (Prefix) to delete is a string.
+            // So we need to validate that it can be casted to string
+            if (is_object($eventId) && !method_exists($eventId, '__toString')) {
+                throw new \InvalidArgumentException("Object of class " . get_class($eventId) . " cannot be cast to string.");
+            }
+            // Also validate that we're not trying to cast arrays, resources or closures
+            if (is_array($eventId) || is_resource($eventId) || $eventId instanceof \Closure) {
+                throw new \InvalidArgumentException("Value of type " . get_debug_type($eventId) . " cannot be cast to string.");
```
Comment (dygland) [inline app/Lib/Tools/AttachmentTool.php:288]: Please note that get_debug_type() is a PHP8 only Method. This is therefore not suitable to migrate to MISP 2.4 without some refactoring.

This could be replaced by the gettype() function (but i chose not to) 
The function is also used on L294
